<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <p id="demo1"></p>

    <input id="demo2" type="text">
    <button type="button" onclick="myfunction()">Test Input</button>
    <p id="p01"></p>

    <!-- HTML Validation -->
    <input type="number" id="demo" min="5" max="10" step="1">

    <script>
        // throw and try to catch

        // The try statement lets you test a block of code for errors.

        // The catch statement lets you handle the error.

        // The throw statement lets you create custom errors.

        // The finally statement lets you execute code, after try and catch, regardless of the result.
        try{
            adddlert("Welcome guest!");
        }
        catch(err){
            console.log(err.message);
        }

        // JavaScript catches adddlert as an error, and executes the catch code to handle it.

        // JavaScript try and catch
        /*

            try {
            Block of code to try
            }
            catch(err) {
            Block of code to handle errors
            }

        */

        // throw statement 
        // throw "too big";
        // throw 500;

        // finally statement
        /*
        
        try {
        Block of code to try
        }
        catch(err) {
        Block of code to handle errors
        }
        finally {
        Block of code to be executed regardless of the try / catch result
        }
                
        */
        
        function myfunction(){
            let message, x;
            message = document.getElementById("p01");
            message.innerHTML = "";
            x = document.getElementById("demo2").value;

            try{
                if(x == "") throw "empty"
                if(isNaN(x)) throw "not a number";
                x = Number(x);
                if(x < 5) throw "too low";
                if(x > 10) throw "too high";
            }
            catch(err){
                message.innerHTML = "Input is " + err;
            }
            finally{
                document.getElementById("demo2"),value = "login success";
            }
        }

        // error name value

        /*
            list of error
            - eval error
            - range error
            - syntax error
            - refreance error
            - type error
            - URI (uniform resource identifier)error

        
        */


        // Eval Error
        // An EvalError indicates an error in the eval() function.


        // Range Error
        let num = 1;
        try{

            num.toPrecision(500);   //1 to 100 range
            // num.toPrecision(100);   //1 to 100 range
        }
        catch(err){
            console.log(err.name);
        }


        // reference Error
        let x;
        try{
            x = y + 1; // y can not be referenced (used)(undefined)
        }
        catch(err){
            console.log(x);
        }


        // syntax error
        try{
            eval("alert('Hello)");  
        }
        catch(err){
            console.log(err.name);      //syntax error
        }


        // type error
        num = 1;
        try{
            num.toUpperCase();
        }
        catch(err){
            console.log(err.name);  //type error
        }

        
        // URI (uniform resource identifier)
        try{
            decodeURI("%%%");
        }
        catch(err){
            console.log(err.name)
        }


        /*
        - range error
        - syntax error
        - eval error
        - type error
        - refrenace error
        - URI error
        
        */

        
        
        



    </script>



</body>

</html>